version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.9.2
    ports:
      - "5601:5601"
